services:
  - type: web
    name: lhdecant-backend
    env: node
    plan: free
    buildCommand: npm run server:build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FIREBASE_PROJECT_ID
        value: lhdecant-57491
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: FIREBASE_AUTH_URI
        value: https://accounts.google.com/o/oauth2/auth
      - key: FIREBASE_TOKEN_URI
        value: https://oauth2.googleapis.com/token
      - key: FIREBASE_AUTH_PROVIDER_X509_CERT_URL
        value: https://www.googleapis.com/oauth2/v1/certs
      - key: FIREBASE_CLIENT_X509_CERT_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        value: 146579938759-92haah9cmejdukbps1krv2vdfd3pla5m.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://lhdecant-backend.onrender.com/api/auth/google/callback
      - key: FRONTEND_URL
        value: https://lhdecant.com
      - key: BACKEND_URL
        value: https://lhdecant-backend.onrender.com
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://lhdecant.com,https://lhdecant-backend.onrender.com,https://lhdecant.netlify.app
