import { admin } from "./storage";

const newPerfumes = [
  {
    name: "Fakhar Black",
    brand: "Lattafa",
    description: "Una fragancia oriental intensa y misteriosa que combina notas de incienso, ámbar y especias exóticas. Perfecta para ocasiones nocturnas y eventos especiales.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["12.00", "20.00", "28.00"],
    category: "unisex",
    notes: ["Incienso", "Ámbar", "Especias", "Sándalo", "Vainilla"],
    imageUrl: "",
    rating: "4.3",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Tobacco Vanille",
    brand: "Tom Ford",
    description: "Una mezcla opulenta y sofisticada que combina el tabaco seco con vainilla cremosa y especias cálidas. Una fragancia unisex que evoca lujo y sensualidad.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["35.00", "65.00", "95.00"],
    category: "unisex",
    notes: ["Tabaco", "Vainilla", "Cacao", "Tonka", "Especias"],
    imageUrl: "",
    rating: "4.8",
    inStock: true,
    showOnHomepage: true,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Le Beau Parfum",
    brand: "Jean Paul Gaultier",
    description: "Una fragancia masculina moderna y atrevida que combina frescura mediterránea con sensualidad. Perfecta para el hombre contemporáneo que busca distinción.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["25.00", "45.00", "65.00"],
    category: "masculine",
    notes: ["Bergamota", "Cardamomo", "Cedro", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.5",
    inStock: true,
    showOnHomepage: true,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Scandal Pour Homme",
    brand: "Jean Paul Gaultier",
    description: "Una fragancia masculina audaz y provocativa que desafía las convenciones. Combina frescura cítrica con notas amaderadas y especiadas.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["22.00", "40.00", "58.00"],
    category: "masculine",
    notes: ["Bergamota", "Pimienta", "Cedro", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.4",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Scandal Pour Homme Absolu",
    brand: "Jean Paul Gaultier",
    description: "La versión más intensa y concentrada de Scandal. Una fragancia masculina poderosa que combina frescura extrema con profundidad amaderada.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["28.00", "50.00", "72.00"],
    category: "masculine",
    notes: ["Bergamota", "Pimienta Negra", "Cedro", "Vetiver", "Ámbar Gris"],
    imageUrl: "",
    rating: "4.6",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Scandal Le Parfum Pour Homme",
    brand: "Jean Paul Gaultier",
    description: "La versión más concentrada y duradera de Scandal. Una fragancia masculina de parfum que combina elegancia con audacia.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["32.00", "58.00", "85.00"],
    category: "masculine",
    notes: ["Bergamota", "Cardamomo", "Cedro", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.7",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Invictus Absolu Parfum",
    brand: "Paco Rabanne",
    description: "La versión más intensa y concentrada de Invictus. Una fragancia masculina de parfum que combina frescura extrema con profundidad amaderada.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["30.00", "55.00", "80.00"],
    category: "masculine",
    notes: ["Pomelo", "Laurel", "Cedro", "Ambergris", "Guayaco"],
    imageUrl: "",
    rating: "4.6",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "One Million",
    brand: "Paco Rabanne",
    description: "Una fragancia masculina icónica que combina frescura cítrica con notas especiadas y amaderadas. Perfecta para el hombre que busca distinción.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["25.00", "45.00", "65.00"],
    category: "masculine",
    notes: ["Bergamota", "Pimienta", "Canela", "Cedro", "Ámbar"],
    imageUrl: "",
    rating: "4.5",
    inStock: true,
    showOnHomepage: true,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Phantom Eau de Toilette",
    brand: "Paco Rabanne",
    description: "Una fragancia masculina futurista que combina tecnología olfativa con notas tradicionales. Una experiencia sensorial única.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["28.00", "50.00", "72.00"],
    category: "masculine",
    notes: ["Bergamota", "Lavanda", "Vetiver", "Ámbar", "Cedro"],
    imageUrl: "",
    rating: "4.4",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Bad Boy Le Parfum",
    brand: "Carolina Herrera",
    description: "Una fragancia masculina audaz y provocativa que combina frescura cítrica con notas especiadas y amaderadas. Para el hombre que no teme destacar.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["26.00", "48.00", "70.00"],
    category: "masculine",
    notes: ["Bergamota", "Pimienta", "Cedro", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.5",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Le Male Elixir",
    brand: "Jean Paul Gaultier",
    description: "La versión más concentrada y sensual de Le Male. Una fragancia masculina de elixir que combina frescura con profundidad amaderada.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["32.00", "58.00", "85.00"],
    category: "masculine",
    notes: ["Bergamota", "Cardamomo", "Cedro", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.7",
    inStock: true,
    showOnHomepage: true,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Le Male",
    brand: "Jean Paul Gaultier",
    description: "Una fragancia masculina icónica que combina frescura mediterránea con sensualidad. Perfecta para el hombre que busca distinción y elegancia.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["24.00", "42.00", "60.00"],
    category: "masculine",
    notes: ["Bergamota", "Lavanda", "Cedro", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.6",
    inStock: true,
    showOnHomepage: true,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Khamrah Qahwa",
    brand: "Lattafa",
    description: "Una fragancia oriental intensa inspirada en el café árabe. Combina notas de café, especias y ámbar para una experiencia olfativa única.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["15.00", "25.00", "35.00"],
    category: "unisex",
    notes: ["Café", "Cardamomo", "Ámbar", "Sándalo", "Vainilla"],
    imageUrl: "",
    rating: "4.4",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Maahir Legacy",
    brand: "Lattafa",
    description: "Una fragancia oriental sofisticada que combina tradición con modernidad. Notas de incienso, ámbar y especias exóticas.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["18.00", "30.00", "42.00"],
    category: "unisex",
    notes: ["Incienso", "Ámbar", "Especias", "Sándalo", "Vainilla"],
    imageUrl: "",
    rating: "4.3",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Hayati Al Maleky",
    brand: "Lattafa",
    description: "Una fragancia oriental real que combina lujo y elegancia. Notas de rosa, ámbar y especias nobles para una experiencia olfativa majestuosa.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["20.00", "35.00", "50.00"],
    category: "unisex",
    notes: ["Rosa", "Ámbar", "Especias", "Sándalo", "Vainilla"],
    imageUrl: "",
    rating: "4.5",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Bleu de Chanel Le Parfum",
    brand: "Chanel",
    description: "La versión más concentrada y sofisticada de Bleu de Chanel. Una fragancia masculina de parfum que combina elegancia con modernidad.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["40.00", "75.00", "110.00"],
    category: "masculine",
    notes: ["Limón", "Menta", "Sándalo", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.8",
    inStock: true,
    showOnHomepage: true,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Myslf Eau de Parfum",
    brand: "Yves Saint Laurent",
    description: "Una fragancia masculina moderna que celebra la autenticidad. Combina frescura cítrica con profundidad amaderada para el hombre contemporáneo.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["30.00", "55.00", "80.00"],
    category: "masculine",
    notes: ["Bergamota", "Lavanda", "Cedro", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.4",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Honor and Glory",
    brand: "Amouage",
    description: "Una fragancia de nicho sofisticada que combina tradición con innovación. Notas de incienso, ámbar y especias nobles para una experiencia olfativa única.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["45.00", "85.00", "125.00"],
    category: "unisex",
    notes: ["Incienso", "Ámbar", "Especias", "Sándalo", "Vainilla"],
    imageUrl: "",
    rating: "4.7",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Montale Tonka",
    brand: "Montale",
    description: "Una fragancia de nicho que celebra la tonka en toda su gloria. Una mezcla opulenta y sensual que combina dulzura con profundidad.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["35.00", "65.00", "95.00"],
    category: "unisex",
    notes: ["Tonka", "Vainilla", "Cacao", "Ámbar", "Sándalo"],
    imageUrl: "",
    rating: "4.6",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Born in Roma",
    brand: "Valentino",
    description: "Una fragancia masculina moderna que celebra la herencia italiana. Combina frescura mediterránea con elegancia contemporánea.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["28.00", "50.00", "72.00"],
    category: "masculine",
    notes: ["Bergamota", "Lavanda", "Cedro", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.5",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Stronger With You",
    brand: "Armani",
    description: "Una fragancia masculina que celebra la conexión humana. Combina frescura cítrica con notas especiadas y amaderadas.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["26.00", "48.00", "70.00"],
    category: "masculine",
    notes: ["Bergamota", "Pimienta", "Cedro", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.6",
    inStock: true,
    showOnHomepage: true,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Mandarin Sky",
    brand: "Kilian",
    description: "Una fragancia de nicho que celebra la mandarina en toda su frescura. Una experiencia olfativa luminosa y vibrante.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["40.00", "75.00", "110.00"],
    category: "unisex",
    notes: ["Mandarina", "Bergamota", "Cedro", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.7",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Asad Bourbon",
    brand: "Lattafa",
    description: "Una fragancia oriental inspirada en el bourbon americano. Combina notas de vainilla, cacao y especias para una experiencia olfativa única.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["16.00", "28.00", "40.00"],
    category: "unisex",
    notes: ["Vainilla", "Cacao", "Especias", "Ámbar", "Sándalo"],
    imageUrl: "",
    rating: "4.3",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Hawas Ice",
    brand: "Rasasi",
    description: "Una fragancia masculina fresca y moderna que combina frescura extrema con profundidad amaderada. Perfecta para el hombre contemporáneo.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["20.00", "35.00", "50.00"],
    category: "masculine",
    notes: ["Bergamota", "Menta", "Cedro", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.4",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Liquid Brum",
    brand: "Lattafa",
    description: "Una fragancia oriental moderna que combina tradición con innovación. Notas de incienso, ámbar y especias exóticas.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["14.00", "24.00", "34.00"],
    category: "unisex",
    notes: ["Incienso", "Ámbar", "Especias", "Sándalo", "Vainilla"],
    imageUrl: "",
    rating: "4.2",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "9 PM",
    brand: "Afnan",
    description: "Una fragancia masculina nocturna que combina frescura cítrica con notas especiadas y amaderadas. Perfecta para ocasiones nocturnas.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["18.00", "32.00", "46.00"],
    category: "masculine",
    notes: ["Bergamota", "Pimienta", "Cedro", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.3",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Perfume Asad",
    brand: "Lattafa",
    description: "Una fragancia oriental intensa que combina notas de incienso, ámbar y especias exóticas. Una experiencia olfativa única y misteriosa.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["15.00", "25.00", "35.00"],
    category: "unisex",
    notes: ["Incienso", "Ámbar", "Especias", "Sándalo", "Vainilla"],
    imageUrl: "",
    rating: "4.4",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Vintage Radio",
    brand: "Lattafa",
    description: "Una fragancia oriental que evoca nostalgia y elegancia. Combina notas de incienso, ámbar y especias nobles para una experiencia olfativa única.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["17.00", "30.00", "43.00"],
    category: "unisex",
    notes: ["Incienso", "Ámbar", "Especias", "Sándalo", "Vainilla"],
    imageUrl: "",
    rating: "4.3",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Jean Lowe Ozure",
    brand: "Lattafa",
    description: "Una fragancia de nicho que combina elegancia con modernidad. Notas de incienso, ámbar y especias nobles para una experiencia olfativa sofisticada.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["22.00", "40.00", "58.00"],
    category: "unisex",
    notes: ["Incienso", "Ámbar", "Especias", "Sándalo", "Vainilla"],
    imageUrl: "",
    rating: "4.5",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Erba Pura",
    brand: "Xerjoff",
    description: "Una fragancia de nicho que celebra la pureza de la naturaleza. Combina frescura cítrica con notas florales y amaderadas para una experiencia olfativa única.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["50.00", "95.00", "140.00"],
    category: "unisex",
    notes: ["Bergamota", "Jazmín", "Cedro", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.8",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Eros",
    brand: "Versace",
    description: "Una fragancia masculina icónica que combina frescura mediterránea con sensualidad. Perfecta para el hombre que busca distinción y elegancia.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["24.00", "42.00", "60.00"],
    category: "masculine",
    notes: ["Bergamota", "Menta", "Cedro", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.6",
    inStock: true,
    showOnHomepage: true,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Homme Intense",
    brand: "Dior",
    description: "La versión más intensa y sofisticada de Dior Homme. Una fragancia masculina de parfum que combina elegancia con modernidad.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["35.00", "65.00", "95.00"],
    category: "masculine",
    notes: ["Bergamota", "Lavanda", "Cedro", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.7",
    inStock: true,
    showOnHomepage: true,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Luna Rossa Ocean Vapo",
    brand: "Prada",
    description: "Una fragancia masculina moderna que celebra la frescura oceánica. Combina notas marinas con profundidad amaderada para una experiencia olfativa única.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["28.00", "50.00", "72.00"],
    category: "masculine",
    notes: ["Bergamota", "Algas", "Cedro", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.5",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Sauvage Elixir",
    brand: "Dior",
    description: "La versión más concentrada y sofisticada de Sauvage. Una fragancia masculina de elixir que combina frescura extrema con profundidad amaderada.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["45.00", "85.00", "125.00"],
    category: "masculine",
    notes: ["Bergamota", "Pimienta", "Cedro", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.8",
    inStock: true,
    showOnHomepage: true,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  },
  {
    name: "Club de Nuit Iconic",
    brand: "Armaf",
    description: "Una fragancia masculina moderna que combina frescura cítrica con notas especiadas y amaderadas. Perfecta para el hombre contemporáneo.",
    sizes: ["5ml", "10ml", "15ml"],
    prices: ["20.00", "35.00", "50.00"],
    category: "masculine",
    notes: ["Bergamota", "Pimienta", "Cedro", "Vetiver", "Ámbar"],
    imageUrl: "",
    rating: "4.4",
    inStock: true,
    showOnHomepage: false,
    isOnOffer: false,
    discountPercentage: "0",
    offerDescription: null,
    createdAt: new Date(),
  }
];

async function addNewPerfumes() {
  try {
    console.log("🚀 Iniciando inserción de nuevos perfumes...");
    
    const batch = admin.firestore().batch();
    let addedCount = 0;
    let skippedCount = 0;

    for (const perfume of newPerfumes) {
      // Verificar si el perfume ya existe
      const existingPerfumes = await admin.firestore()
        .collection('perfumes')
        .where('name', '==', perfume.name)
        .where('brand', '==', perfume.brand)
        .get();

      if (!existingPerfumes.empty) {
        console.log(`⏭️  Saltando ${perfume.name} - ${perfume.brand} (ya existe)`);
        skippedCount++;
        continue;
      }

      // Agregar el perfume
      const perfumeRef = admin.firestore().collection('perfumes').doc();
      batch.set(perfumeRef, {
        ...perfume,
        id: perfumeRef.id,
        createdAt: admin.firestore.FieldValue.serverTimestamp(),
        updatedAt: admin.firestore.FieldValue.serverTimestamp()
      });

      console.log(`✅ Agregando ${perfume.name} - ${perfume.brand}`);
      addedCount++;
    }

    await batch.commit();
    
    console.log("\n🎉 ¡Inserción completada!");
    console.log(`✅ Perfumes agregados: ${addedCount}`);
    console.log(`⏭️  Perfumes saltados: ${skippedCount}`);
    console.log(`📊 Total procesados: ${addedCount + skippedCount}`);
    
  } catch (error) {
    console.error("❌ Error al agregar perfumes:", error);
  }
}

// Ejecutar el script
addNewPerfumes().then(() => {
  console.log("🏁 Script completado");
  process.exit(0);
}).catch((error) => {
  console.error("💥 Error fatal:", error);
  process.exit(1);
}); 